; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v3.3.1-LPC-STM32+7 on Fri May 13 2022 14:38:04 GMT+0800 (中国标准时间)
G1 R1 X0 Y0 Z5 F6000 ; go to 5mm above position of the last print move
G1 R1 X0 Y0 Z0       ; go back to the last print move
M83                  ; relative extruder moves
G1 E0.5 F3600         ; extrude 10mm of filament

