; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.1-LPC-STM32+7 on Fri May 13 2022 14:38:05 GMT+0800 (中国标准时间)
; Wait for set temperatures to be reached
M116 P0

